import "./globals.css";
import "./css/general-sans.css";
// Components
import Navbar from "@/app/components/home/Navbar";

export const metadata = {
  title: "Nethrite",
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-primary-black">
        <main className="">{children}</main>
      </body>
    </html>
  );
}
