import "./globals.css";
import "./css/general-sans.css";
import { Inter } from "next/font/google";

// Components
import Navbar from "@/app/components/home/Navbar";

// Google Font
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Nethrite",
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-primary-black ${inter.className}`}>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
